/* GENERATED by scripts/build_web_data.py -- do not edit by hand.
 *
 * The vetted repo list, the headline counts, and one recorded forge,
 * straight from infra/docker/vetted_repos.json and phase5_output/. Written
 * out so the landing page cannot drift from what the pipeline can actually
 * do. */
import type { StreamRow } from "./api";

export interface VettedRepo {
  repo: string;
  display: string;
  url: string;
  sha: string;
  language: string;
}

export interface ForgeData {
  repos: VettedRepo[];
  headline: { candidates: number; covered: number; admitted: number; gaps: number };
  replay: {
    repo: string;
    display: string;
    commit: string;
    baseline: { total_tests: number; covered_lines: number };
    candidates: number;
    batches: number;
    rows: StreamRow[];
    summary: { challenges_ready: number; test_gaps: number };
  };
  gapsByFile: { repo: string; total: number; files: { path: string; count: number }[] };
}

const DATA: ForgeData = {
  "repos": [
    {
      "repo": "jd__tenacity",
      "display": "jd/tenacity",
      "url": "https://github.com/jd/tenacity",
      "sha": "3e58094d3b",
      "language": "python"
    },
    {
      "repo": "golang-jwt__jwt",
      "display": "golang-jwt/jwt",
      "url": "https://github.com/golang-jwt/jwt",
      "sha": "e9547a11aa",
      "language": "go"
    }
  ],
  "headline": {
    "candidates": 157,
    "covered": 120,
    "admitted": 56,
    "gaps": 48
  },
  "replay": {
    "repo": "jd__tenacity",
    "display": "jd/tenacity",
    "commit": "3e58094d3b",
    "baseline": {
      "total_tests": 183,
      "covered_lines": 120
    },
    "candidates": 120,
    "batches": 15,
    "rows": [
      {
        "id": "r0",
        "operator": "RETURN",
        "verdict": "drop",
        "location": "tenacity/__init__.py:187",
        "tests_red": 49,
        "detail": "too loud"
      },
      {
        "id": "r1",
        "operator": "BOOLEAN",
        "verdict": "gap",
        "location": "tenacity/__init__.py:230",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r2",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r3",
        "operator": "NEGATION",
        "verdict": "drop",
        "location": "tenacity/__init__.py:362",
        "tests_red": 82,
        "detail": "too loud"
      },
      {
        "id": "r4",
        "operator": "RETURN",
        "verdict": "drop",
        "location": "tenacity/__init__.py:364",
        "tests_red": 89,
        "detail": "too loud"
      },
      {
        "id": "r5",
        "operator": "RETURN",
        "verdict": "drop",
        "location": "tenacity/__init__.py:370",
        "tests_red": 88,
        "detail": "too loud"
      },
      {
        "id": "r6",
        "operator": "NEGATION",
        "verdict": "drop",
        "location": "tenacity/__init__.py:382",
        "tests_red": null,
        "detail": "timeout"
      },
      {
        "id": "r7",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 45,
        "detail": "displacement 4"
      },
      {
        "id": "r8",
        "operator": "NEGATION",
        "verdict": "gap",
        "location": "tenacity/__init__.py:425",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r9",
        "operator": "BOOLEAN",
        "verdict": "gap",
        "location": "tenacity/__init__.py:451",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r10",
        "operator": "BOOLEAN",
        "verdict": "drop",
        "location": "tenacity/__init__.py:459",
        "tests_red": null,
        "detail": "timeout"
      },
      {
        "id": "r11",
        "operator": "BOOLEAN",
        "verdict": "gap",
        "location": "tenacity/__init__.py:504",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r12",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 2,
        "detail": "displacement 4"
      },
      {
        "id": "r13",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/__init__.py:560",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r14",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 11,
        "detail": "displacement 4"
      },
      {
        "id": "r15",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/__init__.py:631",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r16",
        "operator": "ARITHMETIC",
        "verdict": "drop",
        "location": "tenacity/__init__.py:637",
        "tests_red": 46,
        "detail": "too loud"
      },
      {
        "id": "r17",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/_utils.py:64",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r18",
        "operator": "COMPARISON",
        "verdict": "gap",
        "location": "tenacity/_utils.py:64",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r19",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/_utils.py:64",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r20",
        "operator": "COMPARISON",
        "verdict": "gap",
        "location": "tenacity/_utils.py:67",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r21",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/_utils.py:67",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r22",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/_utils.py:68",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r23",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/_utils.py:69",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r24",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/_utils.py:70",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r25",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/_utils.py:71",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r26",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/_utils.py:71",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r27",
        "operator": "COMPARISON",
        "verdict": "gap",
        "location": "tenacity/_utils.py:73",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r28",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/_utils.py:73",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r29",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/_utils.py:75",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r30",
        "operator": "COMPARISON",
        "verdict": "gap",
        "location": "tenacity/_utils.py:75",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r31",
        "operator": "COMPARISON",
        "verdict": "gap",
        "location": "tenacity/_utils.py:75",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r32",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/_utils.py:75",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r33",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/_utils.py:77",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r34",
        "operator": "NEGATION",
        "verdict": "gap",
        "location": "tenacity/_utils.py:95",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r35",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r36",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r37",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 19,
        "detail": "displacement 4"
      },
      {
        "id": "r38",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 3,
        "detail": "displacement 4"
      },
      {
        "id": "r39",
        "operator": "RETURN",
        "verdict": "drop",
        "location": "tenacity/asyncio/__init__.py:72",
        "tests_red": 17,
        "detail": "too easy"
      },
      {
        "id": "r40",
        "operator": "NEGATION",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 11,
        "detail": "displacement 2"
      },
      {
        "id": "r41",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 2,
        "detail": "displacement 4"
      },
      {
        "id": "r42",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/asyncio/__init__.py:141",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r43",
        "operator": "NEGATION",
        "verdict": "gap",
        "location": "tenacity/asyncio/__init__.py:157",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r44",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 19,
        "detail": "displacement 4"
      },
      {
        "id": "r45",
        "operator": "NEGATION",
        "verdict": "drop",
        "location": "tenacity/asyncio/__init__.py:184",
        "tests_red": 11,
        "detail": "too easy"
      },
      {
        "id": "r46",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 3,
        "detail": "displacement 4"
      },
      {
        "id": "r47",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 11,
        "detail": "displacement 4"
      },
      {
        "id": "r48",
        "operator": "NEGATION",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 12,
        "detail": "displacement 2"
      },
      {
        "id": "r49",
        "operator": "BOOLEAN",
        "verdict": "gap",
        "location": "tenacity/asyncio/__init__.py:197",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r50",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 2,
        "detail": "displacement 4"
      },
      {
        "id": "r51",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 11,
        "detail": "displacement 4"
      },
      {
        "id": "r52",
        "operator": "NEGATION",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 7,
        "detail": "displacement 2"
      },
      {
        "id": "r53",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r54",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 6,
        "detail": "displacement 4"
      },
      {
        "id": "r55",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r56",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r57",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r58",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r59",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 2,
        "detail": "displacement 4"
      },
      {
        "id": "r60",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/asyncio/retry.py:82",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r61",
        "operator": "NEGATION",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 4,
        "detail": "displacement 4"
      },
      {
        "id": "r62",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 4,
        "detail": "displacement 4"
      },
      {
        "id": "r63",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/asyncio/retry.py:100",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r64",
        "operator": "BOOLEAN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 2,
        "detail": "displacement 4"
      },
      {
        "id": "r65",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 2,
        "detail": "displacement 4"
      },
      {
        "id": "r66",
        "operator": "BOOLEAN",
        "verdict": "drop",
        "location": "tenacity/asyncio/retry.py:137",
        "tests_red": null,
        "detail": "timeout"
      },
      {
        "id": "r67",
        "operator": "NEGATION",
        "verdict": "gap",
        "location": "tenacity/asyncio/retry.py:138",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r68",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 2,
        "detail": "displacement 4"
      },
      {
        "id": "r69",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r70",
        "operator": "BOOLEAN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r71",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 4,
        "detail": "displacement 4"
      },
      {
        "id": "r72",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 3,
        "detail": "displacement 4"
      },
      {
        "id": "r73",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r74",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 4,
        "detail": "displacement 4"
      },
      {
        "id": "r75",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r76",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r77",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/retry.py:71",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r78",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 40,
        "detail": "displacement 4"
      },
      {
        "id": "r79",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 35,
        "detail": "displacement 4"
      },
      {
        "id": "r80",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r81",
        "operator": "NEGATION",
        "verdict": "drop",
        "location": "tenacity/retry.py:157",
        "tests_red": null,
        "detail": "timeout"
      },
      {
        "id": "r82",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/retry.py:163",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r83",
        "operator": "RETURN",
        "verdict": "drop",
        "location": "tenacity/retry.py:194",
        "tests_red": null,
        "detail": "timeout"
      },
      {
        "id": "r84",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/retry.py:197",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r85",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 20,
        "detail": "displacement 4"
      },
      {
        "id": "r86",
        "operator": "NEGATION",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r87",
        "operator": "RETURN",
        "verdict": "drop",
        "location": "tenacity/retry.py:258",
        "tests_red": null,
        "detail": "timeout"
      },
      {
        "id": "r88",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r89",
        "operator": "NEGATION",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 4,
        "detail": "displacement 4"
      },
      {
        "id": "r90",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/retry.py:276",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r91",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 4,
        "detail": "displacement 4"
      },
      {
        "id": "r92",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 2,
        "detail": "displacement 4"
      },
      {
        "id": "r93",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r94",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 2,
        "detail": "displacement 4"
      },
      {
        "id": "r95",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 2,
        "detail": "displacement 4"
      },
      {
        "id": "r96",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/stop.py:72",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r97",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/stop.py:97",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r98",
        "operator": "COMPARISON",
        "verdict": "gap",
        "location": "tenacity/stop.py:97",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r99",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 4,
        "detail": "displacement 4"
      },
      {
        "id": "r100",
        "operator": "COMPARISON",
        "verdict": "gap",
        "location": "tenacity/stop.py:117",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r101",
        "operator": "ARITHMETIC",
        "verdict": "gap",
        "location": "tenacity/stop.py:136",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r102",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 3,
        "detail": "displacement 4"
      },
      {
        "id": "r103",
        "operator": "BOUNDARY",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r104",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 0"
      },
      {
        "id": "r105",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 1,
        "detail": "displacement 4"
      },
      {
        "id": "r106",
        "operator": "ARITHMETIC",
        "verdict": "gap",
        "location": "tenacity/wait.py:91",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r107",
        "operator": "NEGATION",
        "verdict": "drop",
        "location": "tenacity/wait.py:127",
        "tests_red": 3,
        "detail": "too easy"
      },
      {
        "id": "r108",
        "operator": "RETURN",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 2,
        "detail": "displacement 4"
      },
      {
        "id": "r109",
        "operator": "ARITHMETIC",
        "verdict": "gap",
        "location": "tenacity/wait.py:197",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r110",
        "operator": "RETURN",
        "verdict": "gap",
        "location": "tenacity/wait.py:198",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r111",
        "operator": "COMPARISON",
        "verdict": "gap",
        "location": "tenacity/wait.py:230",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r112",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/wait.py:230",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r113",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/wait.py:231",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r114",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/wait.py:232",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r115",
        "operator": "RETURN",
        "verdict": "drop",
        "location": "tenacity/wait.py:238",
        "tests_red": 6,
        "detail": "too easy"
      },
      {
        "id": "r116",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/wait.py:300",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r117",
        "operator": "BOUNDARY",
        "verdict": "drop",
        "location": "tenacity/wait.py:300",
        "tests_red": 2,
        "detail": "too easy"
      },
      {
        "id": "r118",
        "operator": "BOUNDARY",
        "verdict": "gap",
        "location": "tenacity/wait.py:305",
        "tests_red": 0,
        "detail": "test gap → report"
      },
      {
        "id": "r119",
        "operator": "ARITHMETIC",
        "verdict": "keep",
        "location": "░░░░░░.py:░░░",
        "tests_red": 5,
        "detail": "displacement 4"
      }
    ],
    "summary": {
      "challenges_ready": 56,
      "test_gaps": 48
    }
  },
  "gapsByFile": {
    "repo": "jd__tenacity",
    "total": 48,
    "files": [
      {
        "path": "tenacity/_utils.py",
        "count": 18
      },
      {
        "path": "tenacity/wait.py",
        "count": 9
      },
      {
        "path": "tenacity/__init__.py",
        "count": 6
      },
      {
        "path": "tenacity/stop.py",
        "count": 5
      },
      {
        "path": "tenacity/retry.py",
        "count": 4
      },
      {
        "path": "tenacity/asyncio/__init__.py",
        "count": 3
      },
      {
        "path": "tenacity/asyncio/retry.py",
        "count": 3
      }
    ]
  }
};

export const VETTED_REPOS: readonly VettedRepo[] = DATA.repos;
export const HEADLINE = DATA.headline;
export const GAPS_BY_FILE = DATA.gapsByFile;
export const REPLAY = DATA.replay;
