"""Generates web/lib/forge-data.ts from the real pipeline output.

Three things the web app should never be able to get wrong by hand:

  * the vetted repo list, which drives the landing page's "try" chips. They
    used to be hardcoded and had drifted to two repos that are not vetted, so
    clicking one gave an error.
  * the headline counts (candidates, covered, admitted, gaps), which are the
    proof there is a filter at all.
  * a recorded generation stream, so the landing page can replay a real forge
    instead of sitting idle.

Run it whenever phase5_output changes:

    python scripts/build_web_data.py

The output is committed. If an input is missing the existing file is kept and
this exits 0, so a build on a machine without phase5_output still works.
"""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VETTED = ROOT / "infra" / "docker" / "vetted_repos.json"
REPORT = ROOT / "phase5_output" / "run_report.json"
SELECTION = ROOT / "phase5_output" / "selection.json"
OUTPUT = ROOT / "web" / "lib" / "forge-data.ts"

# Must match cloud/handlers/fn_api.py. A learner who can read the location off
# the stream has already solved the challenge.
MASKED_LOCATION = "░░░░░░.py:░░░"

DROP_DETAIL = {
    "DROP_too_loud": "too loud",
    "DROP_low_score": "too easy",
    "DROP_timeout": "timeout",
    "DROP_catastrophic": "import error",
}
DROP_SHOWS_RED = {"DROP_too_loud", "DROP_low_score"}


def stream_row(record: dict, index: int) -> dict:
    """The same shape fn_api._stream_row produces, from a selection record."""
    site = record["site"]
    outcome = record["outcome"]
    location = f"{site['path']}:{site['lineno']}"
    failing = len(record.get("failing_tests") or [])
    row = {"id": f"r{index}", "operator": site["operator_id"]}

    if outcome == "ADMITTED":
        return {
            **row,
            "verdict": "keep",
            "location": MASKED_LOCATION,
            "tests_red": failing,
            "detail": f"displacement {record['score_breakdown']['displacement']}",
        }
    if outcome == "TEST_GAP":
        return {**row, "verdict": "gap", "location": location, "tests_red": 0, "detail": "test gap → report"}
    return {
        **row,
        "verdict": "drop",
        "location": location,
        "tests_red": failing if outcome in DROP_SHOWS_RED else None,
        "detail": DROP_DETAIL.get(outcome, outcome.lower()),
    }


def main() -> None:
    missing = [p for p in (VETTED, REPORT, SELECTION) if not p.exists()]
    if missing:
        print(f"skipping: {', '.join(str(p) for p in missing)} not found; keeping {OUTPUT.name}")
        return

    vetted = json.loads(VETTED.read_text(encoding="utf-8"))["repos"]
    report = json.loads(REPORT.read_text(encoding="utf-8"))
    selection = json.loads(SELECTION.read_text(encoding="utf-8"))

    repos = [
        {
            # "jd__tenacity" is how the API keys a repo; "jd/tenacity" is how a
            # person types it into the landing page.
            "repo": entry["name"],
            "display": entry["url"].removeprefix("https://github.com/"),
            "url": entry["url"],
            "sha": entry["sha"][:10],
        }
        for entry in vetted
    ]

    counts = report["counts"]
    rows = [stream_row(record, i) for i, record in enumerate(selection["results"])]

    by_file = Counter(gap["path"] for gap in report["gaps"])
    gap_files = [{"path": path, "count": count} for path, count in by_file.most_common()]

    payload = {
        "repos": repos,
        "headline": {
            "candidates": counts["candidates_generated"],
            "covered": counts["candidates_on_covered_lines"],
            "admitted": counts["admitted"],
            "gaps": counts["test_gaps"],
        },
        "replay": {
            "repo": report["repo"],
            "display": next((r["display"] for r in repos if r["repo"] == report["repo"]), report["repo"]),
            "commit": report["commit_sha"][:10],
            "baseline": {
                "total_tests": report["baseline"]["total_tests"],
                "covered_lines": counts["candidates_on_covered_lines"],
            },
            "candidates": counts["candidates_on_covered_lines"],
            "batches": 15,
            "rows": rows,
            "summary": {"challenges_ready": counts["admitted"], "test_gaps": counts["test_gaps"]},
        },
        "gapsByFile": {"repo": report["repo"], "total": counts["test_gaps"], "files": gap_files},
    }

    body = json.dumps(payload, indent=2, ensure_ascii=False)
    header = [
        "/* GENERATED by scripts/build_web_data.py -- do not edit by hand.",
        " *",
        " * The vetted repo list, the headline counts, and one recorded forge,",
        " * straight from infra/docker/vetted_repos.json and phase5_output/. Written",
        " * out so the landing page cannot drift from what the pipeline can actually",
        " * do. */",
        'import type { StreamRow } from "./api";',
        "",
        "export interface VettedRepo {",
        "  repo: string;",
        "  display: string;",
        "  url: string;",
        "  sha: string;",
        "}",
        "",
        "export interface ForgeData {",
        "  repos: VettedRepo[];",
        "  headline: { candidates: number; covered: number; admitted: number; gaps: number };",
        "  replay: {",
        "    repo: string;",
        "    display: string;",
        "    commit: string;",
        "    baseline: { total_tests: number; covered_lines: number };",
        "    candidates: number;",
        "    batches: number;",
        "    rows: StreamRow[];",
        "    summary: { challenges_ready: number; test_gaps: number };",
        "  };",
        "  gapsByFile: { repo: string; total: number; files: { path: string; count: number }[] };",
        "}",
        "",
    ]
    footer = [
        "",
        "export const VETTED_REPOS: readonly VettedRepo[] = DATA.repos;",
        "export const HEADLINE = DATA.headline;",
        "export const GAPS_BY_FILE = DATA.gapsByFile;",
        "export const REPLAY = DATA.replay;",
        "",
    ]
    lines = [*header, f"const DATA: ForgeData = {body};", *footer]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(repos)} vetted repo(s), {len(rows)} stream rows")


if __name__ == "__main__":
    main()
